"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ProvidedSource:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ProvidedSourceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ProvidedSource.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PROVIDED_SOURCE_NOT_SET: _ProvidedSource.ValueType  # 0
    ENV_VAR: _ProvidedSource.ValueType  # 1

class ProvidedSource(_ProvidedSource, metaclass=_ProvidedSourceEnumTypeWrapper): ...

PROVIDED_SOURCE_NOT_SET: ProvidedSource.ValueType  # 0
ENV_VAR: ProvidedSource.ValueType  # 1
global___ProvidedSource = ProvidedSource

class _ConfigType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ConfigTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ConfigType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NOT_SET_CONFIG_TYPE: _ConfigType.ValueType  # 0
    """proto null"""
    CONFIG: _ConfigType.ValueType  # 1
    FEATURE_FLAG: _ConfigType.ValueType  # 2
    LOG_LEVEL: _ConfigType.ValueType  # 3
    SEGMENT: _ConfigType.ValueType  # 4
    LIMIT_DEFINITION: _ConfigType.ValueType  # 5
    DELETED: _ConfigType.ValueType  # 6

class ConfigType(_ConfigType, metaclass=_ConfigTypeEnumTypeWrapper): ...

NOT_SET_CONFIG_TYPE: ConfigType.ValueType  # 0
"""proto null"""
CONFIG: ConfigType.ValueType  # 1
FEATURE_FLAG: ConfigType.ValueType  # 2
LOG_LEVEL: ConfigType.ValueType  # 3
SEGMENT: ConfigType.ValueType  # 4
LIMIT_DEFINITION: ConfigType.ValueType  # 5
DELETED: ConfigType.ValueType  # 6
global___ConfigType = ConfigType

class _LogLevel:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LogLevelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LogLevel.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NOT_SET_LOG_LEVEL: _LogLevel.ValueType  # 0
    TRACE: _LogLevel.ValueType  # 1
    DEBUG: _LogLevel.ValueType  # 2
    INFO: _LogLevel.ValueType  # 3
    WARN: _LogLevel.ValueType  # 5
    """NOTICE = 4;"""
    ERROR: _LogLevel.ValueType  # 6
    FATAL: _LogLevel.ValueType  # 9
    """CRITICAL = 7;
    ALERT = 8;
    """

class LogLevel(_LogLevel, metaclass=_LogLevelEnumTypeWrapper): ...

NOT_SET_LOG_LEVEL: LogLevel.ValueType  # 0
TRACE: LogLevel.ValueType  # 1
DEBUG: LogLevel.ValueType  # 2
INFO: LogLevel.ValueType  # 3
WARN: LogLevel.ValueType  # 5
"""NOTICE = 4;"""
ERROR: LogLevel.ValueType  # 6
FATAL: LogLevel.ValueType  # 9
"""CRITICAL = 7;
ALERT = 8;
"""
global___LogLevel = LogLevel

class _OnFailure:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _OnFailureEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_OnFailure.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NOT_SET: _OnFailure.ValueType  # 0
    LOG_AND_PASS: _OnFailure.ValueType  # 1
    LOG_AND_FAIL: _OnFailure.ValueType  # 2
    THROW: _OnFailure.ValueType  # 3

class OnFailure(_OnFailure, metaclass=_OnFailureEnumTypeWrapper): ...

NOT_SET: OnFailure.ValueType  # 0
LOG_AND_PASS: OnFailure.ValueType  # 1
LOG_AND_FAIL: OnFailure.ValueType  # 2
THROW: OnFailure.ValueType  # 3
global___OnFailure = OnFailure

@typing_extensions.final
class ConfigServicePointer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECT_ID_FIELD_NUMBER: builtins.int
    START_AT_ID_FIELD_NUMBER: builtins.int
    PROJECT_ENV_ID_FIELD_NUMBER: builtins.int
    project_id: builtins.int
    start_at_id: builtins.int
    project_env_id: builtins.int
    def __init__(
        self,
        *,
        project_id: builtins.int = ...,
        start_at_id: builtins.int = ...,
        project_env_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["project_env_id", b"project_env_id", "project_id", b"project_id", "start_at_id", b"start_at_id"]) -> None: ...

global___ConfigServicePointer = ConfigServicePointer

@typing_extensions.final
class ConfigValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INT_FIELD_NUMBER: builtins.int
    STRING_FIELD_NUMBER: builtins.int
    BYTES_FIELD_NUMBER: builtins.int
    DOUBLE_FIELD_NUMBER: builtins.int
    BOOL_FIELD_NUMBER: builtins.int
    WEIGHTED_VALUES_FIELD_NUMBER: builtins.int
    LIMIT_DEFINITION_FIELD_NUMBER: builtins.int
    LOG_LEVEL_FIELD_NUMBER: builtins.int
    STRING_LIST_FIELD_NUMBER: builtins.int
    INT_RANGE_FIELD_NUMBER: builtins.int
    PROVIDED_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    JSON_FIELD_NUMBER: builtins.int
    CONFIDENTIAL_FIELD_NUMBER: builtins.int
    DECRYPT_WITH_FIELD_NUMBER: builtins.int
    int: builtins.int
    string: builtins.str
    bytes: builtins.bytes
    double: builtins.float
    bool: builtins.bool
    @property
    def weighted_values(self) -> global___WeightedValues: ...
    @property
    def limit_definition(self) -> global___LimitDefinition: ...
    log_level: global___LogLevel.ValueType
    @property
    def string_list(self) -> global___StringList: ...
    @property
    def int_range(self) -> global___IntRange: ...
    @property
    def provided(self) -> global___Provided: ...
    @property
    def duration(self) -> global___IsoDuration: ...
    @property
    def json(self) -> global___Json: ...
    confidential: builtins.bool
    """don't log or telemetry this value"""
    decrypt_with: builtins.str
    """key name to decrypt with"""
    def __init__(
        self,
        *,
        int: builtins.int = ...,
        string: builtins.str = ...,
        bytes: builtins.bytes = ...,
        double: builtins.float = ...,
        bool: builtins.bool = ...,
        weighted_values: global___WeightedValues | None = ...,
        limit_definition: global___LimitDefinition | None = ...,
        log_level: global___LogLevel.ValueType = ...,
        string_list: global___StringList | None = ...,
        int_range: global___IntRange | None = ...,
        provided: global___Provided | None = ...,
        duration: global___IsoDuration | None = ...,
        json: global___Json | None = ...,
        confidential: builtins.bool | None = ...,
        decrypt_with: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_confidential", b"_confidential", "_decrypt_with", b"_decrypt_with", "bool", b"bool", "bytes", b"bytes", "confidential", b"confidential", "decrypt_with", b"decrypt_with", "double", b"double", "duration", b"duration", "int", b"int", "int_range", b"int_range", "json", b"json", "limit_definition", b"limit_definition", "log_level", b"log_level", "provided", b"provided", "string", b"string", "string_list", b"string_list", "type", b"type", "weighted_values", b"weighted_values"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_confidential", b"_confidential", "_decrypt_with", b"_decrypt_with", "bool", b"bool", "bytes", b"bytes", "confidential", b"confidential", "decrypt_with", b"decrypt_with", "double", b"double", "duration", b"duration", "int", b"int", "int_range", b"int_range", "json", b"json", "limit_definition", b"limit_definition", "log_level", b"log_level", "provided", b"provided", "string", b"string", "string_list", b"string_list", "type", b"type", "weighted_values", b"weighted_values"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_confidential", b"_confidential"]) -> typing_extensions.Literal["confidential"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_decrypt_with", b"_decrypt_with"]) -> typing_extensions.Literal["decrypt_with"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["type", b"type"]) -> typing_extensions.Literal["int", "string", "bytes", "double", "bool", "weighted_values", "limit_definition", "log_level", "string_list", "int_range", "provided", "duration", "json"] | None: ...

global___ConfigValue = ConfigValue

@typing_extensions.final
class Json(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JSON_FIELD_NUMBER: builtins.int
    json: builtins.str
    def __init__(
        self,
        *,
        json: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["json", b"json"]) -> None: ...

global___Json = Json

@typing_extensions.final
class IsoDuration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEFINITION_FIELD_NUMBER: builtins.int
    definition: builtins.str
    """value is eg P1h30s"""
    def __init__(
        self,
        *,
        definition: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["definition", b"definition"]) -> None: ...

global___IsoDuration = IsoDuration

@typing_extensions.final
class Provided(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCE_FIELD_NUMBER: builtins.int
    LOOKUP_FIELD_NUMBER: builtins.int
    source: global___ProvidedSource.ValueType
    lookup: builtins.str
    """eg MY_ENV_VAR"""
    def __init__(
        self,
        *,
        source: global___ProvidedSource.ValueType | None = ...,
        lookup: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_lookup", b"_lookup", "_source", b"_source", "lookup", b"lookup", "source", b"source"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_lookup", b"_lookup", "_source", b"_source", "lookup", b"lookup", "source", b"source"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_lookup", b"_lookup"]) -> typing_extensions.Literal["lookup"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_source", b"_source"]) -> typing_extensions.Literal["source"] | None: ...

global___Provided = Provided

@typing_extensions.final
class IntRange(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    start: builtins.int
    """if empty treat as Long.MIN_VALUE. Inclusive"""
    end: builtins.int
    """if empty treat as Long.MAX_VALUE. Exclusive"""
    def __init__(
        self,
        *,
        start: builtins.int | None = ...,
        end: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_end", b"_end", "_start", b"_start", "end", b"end", "start", b"start"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_end", b"_end", "_start", b"_start", "end", b"end", "start", b"start"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_end", b"_end"]) -> typing_extensions.Literal["end"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_start", b"_start"]) -> typing_extensions.Literal["start"] | None: ...

global___IntRange = IntRange

@typing_extensions.final
class StringList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___StringList = StringList

@typing_extensions.final
class WeightedValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WEIGHT_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    weight: builtins.int
    """out of 1000"""
    @property
    def value(self) -> global___ConfigValue: ...
    def __init__(
        self,
        *,
        weight: builtins.int = ...,
        value: global___ConfigValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["value", b"value", "weight", b"weight"]) -> None: ...

global___WeightedValue = WeightedValue

@typing_extensions.final
class WeightedValues(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WEIGHTED_VALUES_FIELD_NUMBER: builtins.int
    HASH_BY_PROPERTY_NAME_FIELD_NUMBER: builtins.int
    @property
    def weighted_values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WeightedValue]: ...
    hash_by_property_name: builtins.str
    def __init__(
        self,
        *,
        weighted_values: collections.abc.Iterable[global___WeightedValue] | None = ...,
        hash_by_property_name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_hash_by_property_name", b"_hash_by_property_name", "hash_by_property_name", b"hash_by_property_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_hash_by_property_name", b"_hash_by_property_name", "hash_by_property_name", b"hash_by_property_name", "weighted_values", b"weighted_values"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_hash_by_property_name", b"_hash_by_property_name"]) -> typing_extensions.Literal["hash_by_property_name"] | None: ...

global___WeightedValues = WeightedValues

@typing_extensions.final
class ApiKeyMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    key_id: builtins.str
    """numeric currently, but making it string will be more flexible over time"""
    user_id: builtins.str
    """ditto"""
    def __init__(
        self,
        *,
        key_id: builtins.str | None = ...,
        user_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_key_id", b"_key_id", "_user_id", b"_user_id", "key_id", b"key_id", "user_id", b"user_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_key_id", b"_key_id", "_user_id", b"_user_id", "key_id", b"key_id", "user_id", b"user_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_key_id", b"_key_id"]) -> typing_extensions.Literal["key_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_user_id", b"_user_id"]) -> typing_extensions.Literal["user_id"] | None: ...

global___ApiKeyMetadata = ApiKeyMetadata

@typing_extensions.final
class Configs(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIGS_FIELD_NUMBER: builtins.int
    CONFIG_SERVICE_POINTER_FIELD_NUMBER: builtins.int
    APIKEY_METADATA_FIELD_NUMBER: builtins.int
    DEFAULT_CONTEXT_FIELD_NUMBER: builtins.int
    KEEP_ALIVE_FIELD_NUMBER: builtins.int
    @property
    def configs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Config]: ...
    @property
    def config_service_pointer(self) -> global___ConfigServicePointer: ...
    @property
    def apikey_metadata(self) -> global___ApiKeyMetadata: ...
    @property
    def default_context(self) -> global___ContextSet: ...
    keep_alive: builtins.bool
    def __init__(
        self,
        *,
        configs: collections.abc.Iterable[global___Config] | None = ...,
        config_service_pointer: global___ConfigServicePointer | None = ...,
        apikey_metadata: global___ApiKeyMetadata | None = ...,
        default_context: global___ContextSet | None = ...,
        keep_alive: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_apikey_metadata", b"_apikey_metadata", "_default_context", b"_default_context", "_keep_alive", b"_keep_alive", "apikey_metadata", b"apikey_metadata", "config_service_pointer", b"config_service_pointer", "default_context", b"default_context", "keep_alive", b"keep_alive"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_apikey_metadata", b"_apikey_metadata", "_default_context", b"_default_context", "_keep_alive", b"_keep_alive", "apikey_metadata", b"apikey_metadata", "config_service_pointer", b"config_service_pointer", "configs", b"configs", "default_context", b"default_context", "keep_alive", b"keep_alive"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_apikey_metadata", b"_apikey_metadata"]) -> typing_extensions.Literal["apikey_metadata"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_default_context", b"_default_context"]) -> typing_extensions.Literal["default_context"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_keep_alive", b"_keep_alive"]) -> typing_extensions.Literal["keep_alive"] | None: ...

global___Configs = Configs

@typing_extensions.final
class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ValueType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ValueTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Config._ValueType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NOT_SET_VALUE_TYPE: Config._ValueType.ValueType  # 0
        """proto null"""
        INT: Config._ValueType.ValueType  # 1
        STRING: Config._ValueType.ValueType  # 2
        BYTES: Config._ValueType.ValueType  # 3
        DOUBLE: Config._ValueType.ValueType  # 4
        BOOL: Config._ValueType.ValueType  # 5
        LIMIT_DEFINITION: Config._ValueType.ValueType  # 7
        LOG_LEVEL: Config._ValueType.ValueType  # 9
        STRING_LIST: Config._ValueType.ValueType  # 10
        INT_RANGE: Config._ValueType.ValueType  # 11
        DURATION: Config._ValueType.ValueType  # 12
        JSON: Config._ValueType.ValueType  # 13

    class ValueType(_ValueType, metaclass=_ValueTypeEnumTypeWrapper): ...
    NOT_SET_VALUE_TYPE: Config.ValueType.ValueType  # 0
    """proto null"""
    INT: Config.ValueType.ValueType  # 1
    STRING: Config.ValueType.ValueType  # 2
    BYTES: Config.ValueType.ValueType  # 3
    DOUBLE: Config.ValueType.ValueType  # 4
    BOOL: Config.ValueType.ValueType  # 5
    LIMIT_DEFINITION: Config.ValueType.ValueType  # 7
    LOG_LEVEL: Config.ValueType.ValueType  # 9
    STRING_LIST: Config.ValueType.ValueType  # 10
    INT_RANGE: Config.ValueType.ValueType  # 11
    DURATION: Config.ValueType.ValueType  # 12
    JSON: Config.ValueType.ValueType  # 13

    ID_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    CHANGED_BY_FIELD_NUMBER: builtins.int
    ROWS_FIELD_NUMBER: builtins.int
    ALLOWABLE_VALUES_FIELD_NUMBER: builtins.int
    CONFIG_TYPE_FIELD_NUMBER: builtins.int
    DRAFT_ID_FIELD_NUMBER: builtins.int
    VALUE_TYPE_FIELD_NUMBER: builtins.int
    SEND_TO_CLIENT_SDK_FIELD_NUMBER: builtins.int
    id: builtins.int
    project_id: builtins.int
    key: builtins.str
    @property
    def changed_by(self) -> global___ChangedBy: ...
    @property
    def rows(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ConfigRow]: ...
    @property
    def allowable_values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ConfigValue]: ...
    config_type: global___ConfigType.ValueType
    draft_id: builtins.int
    value_type: global___Config.ValueType.ValueType
    send_to_client_sdk: builtins.bool
    """default value of a boolean in proto3 is false"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        project_id: builtins.int = ...,
        key: builtins.str = ...,
        changed_by: global___ChangedBy | None = ...,
        rows: collections.abc.Iterable[global___ConfigRow] | None = ...,
        allowable_values: collections.abc.Iterable[global___ConfigValue] | None = ...,
        config_type: global___ConfigType.ValueType = ...,
        draft_id: builtins.int | None = ...,
        value_type: global___Config.ValueType.ValueType = ...,
        send_to_client_sdk: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_draft_id", b"_draft_id", "changed_by", b"changed_by", "draft_id", b"draft_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_draft_id", b"_draft_id", "allowable_values", b"allowable_values", "changed_by", b"changed_by", "config_type", b"config_type", "draft_id", b"draft_id", "id", b"id", "key", b"key", "project_id", b"project_id", "rows", b"rows", "send_to_client_sdk", b"send_to_client_sdk", "value_type", b"value_type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_draft_id", b"_draft_id"]) -> typing_extensions.Literal["draft_id"] | None: ...

global___Config = Config

@typing_extensions.final
class ChangedBy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    API_KEY_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.int
    email: builtins.str
    api_key_id: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.int = ...,
        email: builtins.str = ...,
        api_key_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["api_key_id", b"api_key_id", "email", b"email", "user_id", b"user_id"]) -> None: ...

global___ChangedBy = ChangedBy

@typing_extensions.final
class ConfigRow(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class PropertiesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___ConfigValue: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___ConfigValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    PROJECT_ENV_ID_FIELD_NUMBER: builtins.int
    VALUES_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    project_env_id: builtins.int
    """one row per project_env_id"""
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ConditionalValue]: ...
    @property
    def properties(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___ConfigValue]:
        """can store "activated" """
    def __init__(
        self,
        *,
        project_env_id: builtins.int | None = ...,
        values: collections.abc.Iterable[global___ConditionalValue] | None = ...,
        properties: collections.abc.Mapping[builtins.str, global___ConfigValue] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_project_env_id", b"_project_env_id", "project_env_id", b"project_env_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_project_env_id", b"_project_env_id", "project_env_id", b"project_env_id", "properties", b"properties", "values", b"values"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_project_env_id", b"_project_env_id"]) -> typing_extensions.Literal["project_env_id"] | None: ...

global___ConfigRow = ConfigRow

@typing_extensions.final
class ConditionalValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CRITERIA_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    @property
    def criteria(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Criterion]:
        """if all criteria match, then the rule is matched and value is returned"""
    @property
    def value(self) -> global___ConfigValue: ...
    def __init__(
        self,
        *,
        criteria: collections.abc.Iterable[global___Criterion] | None = ...,
        value: global___ConfigValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["criteria", b"criteria", "value", b"value"]) -> None: ...

global___ConditionalValue = ConditionalValue

@typing_extensions.final
class Criterion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _CriterionOperator:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _CriterionOperatorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Criterion._CriterionOperator.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NOT_SET: Criterion._CriterionOperator.ValueType  # 0
        """proto null"""
        LOOKUP_KEY_IN: Criterion._CriterionOperator.ValueType  # 1
        LOOKUP_KEY_NOT_IN: Criterion._CriterionOperator.ValueType  # 2
        IN_SEG: Criterion._CriterionOperator.ValueType  # 3
        NOT_IN_SEG: Criterion._CriterionOperator.ValueType  # 4
        ALWAYS_TRUE: Criterion._CriterionOperator.ValueType  # 5
        PROP_IS_ONE_OF: Criterion._CriterionOperator.ValueType  # 6
        PROP_IS_NOT_ONE_OF: Criterion._CriterionOperator.ValueType  # 7
        PROP_ENDS_WITH_ONE_OF: Criterion._CriterionOperator.ValueType  # 8
        PROP_DOES_NOT_END_WITH_ONE_OF: Criterion._CriterionOperator.ValueType  # 9
        HIERARCHICAL_MATCH: Criterion._CriterionOperator.ValueType  # 10
        IN_INT_RANGE: Criterion._CriterionOperator.ValueType  # 11
        PROP_STARTS_WITH_ONE_OF: Criterion._CriterionOperator.ValueType  # 12
        PROP_DOES_NOT_START_WITH_ONE_OF: Criterion._CriterionOperator.ValueType  # 13
        PROP_CONTAINS_ONE_OF: Criterion._CriterionOperator.ValueType  # 14
        PROP_DOES_NOT_CONTAIN_ONE_OF: Criterion._CriterionOperator.ValueType  # 15
        PROP_LESS_THAN: Criterion._CriterionOperator.ValueType  # 16
        PROP_LESS_THAN_OR_EQUAL: Criterion._CriterionOperator.ValueType  # 17
        PROP_GREATER_THAN: Criterion._CriterionOperator.ValueType  # 18
        PROP_GREATER_THAN_OR_EQUAL: Criterion._CriterionOperator.ValueType  # 19
        PROP_BEFORE: Criterion._CriterionOperator.ValueType  # 20
        PROP_AFTER: Criterion._CriterionOperator.ValueType  # 21
        PROP_MATCHES: Criterion._CriterionOperator.ValueType  # 22
        PROP_DOES_NOT_MATCH: Criterion._CriterionOperator.ValueType  # 23
        PROP_SEMVER_LESS_THAN: Criterion._CriterionOperator.ValueType  # 24
        PROP_SEMVER_EQUAL: Criterion._CriterionOperator.ValueType  # 25
        PROP_SEMVER_GREATER_THAN: Criterion._CriterionOperator.ValueType  # 26

    class CriterionOperator(_CriterionOperator, metaclass=_CriterionOperatorEnumTypeWrapper): ...
    NOT_SET: Criterion.CriterionOperator.ValueType  # 0
    """proto null"""
    LOOKUP_KEY_IN: Criterion.CriterionOperator.ValueType  # 1
    LOOKUP_KEY_NOT_IN: Criterion.CriterionOperator.ValueType  # 2
    IN_SEG: Criterion.CriterionOperator.ValueType  # 3
    NOT_IN_SEG: Criterion.CriterionOperator.ValueType  # 4
    ALWAYS_TRUE: Criterion.CriterionOperator.ValueType  # 5
    PROP_IS_ONE_OF: Criterion.CriterionOperator.ValueType  # 6
    PROP_IS_NOT_ONE_OF: Criterion.CriterionOperator.ValueType  # 7
    PROP_ENDS_WITH_ONE_OF: Criterion.CriterionOperator.ValueType  # 8
    PROP_DOES_NOT_END_WITH_ONE_OF: Criterion.CriterionOperator.ValueType  # 9
    HIERARCHICAL_MATCH: Criterion.CriterionOperator.ValueType  # 10
    IN_INT_RANGE: Criterion.CriterionOperator.ValueType  # 11
    PROP_STARTS_WITH_ONE_OF: Criterion.CriterionOperator.ValueType  # 12
    PROP_DOES_NOT_START_WITH_ONE_OF: Criterion.CriterionOperator.ValueType  # 13
    PROP_CONTAINS_ONE_OF: Criterion.CriterionOperator.ValueType  # 14
    PROP_DOES_NOT_CONTAIN_ONE_OF: Criterion.CriterionOperator.ValueType  # 15
    PROP_LESS_THAN: Criterion.CriterionOperator.ValueType  # 16
    PROP_LESS_THAN_OR_EQUAL: Criterion.CriterionOperator.ValueType  # 17
    PROP_GREATER_THAN: Criterion.CriterionOperator.ValueType  # 18
    PROP_GREATER_THAN_OR_EQUAL: Criterion.CriterionOperator.ValueType  # 19
    PROP_BEFORE: Criterion.CriterionOperator.ValueType  # 20
    PROP_AFTER: Criterion.CriterionOperator.ValueType  # 21
    PROP_MATCHES: Criterion.CriterionOperator.ValueType  # 22
    PROP_DOES_NOT_MATCH: Criterion.CriterionOperator.ValueType  # 23
    PROP_SEMVER_LESS_THAN: Criterion.CriterionOperator.ValueType  # 24
    PROP_SEMVER_EQUAL: Criterion.CriterionOperator.ValueType  # 25
    PROP_SEMVER_GREATER_THAN: Criterion.CriterionOperator.ValueType  # 26

    PROPERTY_NAME_FIELD_NUMBER: builtins.int
    OPERATOR_FIELD_NUMBER: builtins.int
    VALUE_TO_MATCH_FIELD_NUMBER: builtins.int
    property_name: builtins.str
    operator: global___Criterion.CriterionOperator.ValueType
    @property
    def value_to_match(self) -> global___ConfigValue: ...
    def __init__(
        self,
        *,
        property_name: builtins.str = ...,
        operator: global___Criterion.CriterionOperator.ValueType = ...,
        value_to_match: global___ConfigValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["value_to_match", b"value_to_match"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["operator", b"operator", "property_name", b"property_name", "value_to_match", b"value_to_match"]) -> None: ...

global___Criterion = Criterion

@typing_extensions.final
class Loggers(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOGGERS_FIELD_NUMBER: builtins.int
    START_AT_FIELD_NUMBER: builtins.int
    END_AT_FIELD_NUMBER: builtins.int
    INSTANCE_HASH_FIELD_NUMBER: builtins.int
    NAMESPACE_FIELD_NUMBER: builtins.int
    @property
    def loggers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Logger]: ...
    start_at: builtins.int
    end_at: builtins.int
    instance_hash: builtins.str
    """random UUID generated on startup - represents the server so we can aggregate"""
    namespace: builtins.str
    def __init__(
        self,
        *,
        loggers: collections.abc.Iterable[global___Logger] | None = ...,
        start_at: builtins.int = ...,
        end_at: builtins.int = ...,
        instance_hash: builtins.str = ...,
        namespace: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_namespace", b"_namespace", "namespace", b"namespace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_namespace", b"_namespace", "end_at", b"end_at", "instance_hash", b"instance_hash", "loggers", b"loggers", "namespace", b"namespace", "start_at", b"start_at"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_namespace", b"_namespace"]) -> typing_extensions.Literal["namespace"] | None: ...

global___Loggers = Loggers

@typing_extensions.final
class Logger(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOGGER_NAME_FIELD_NUMBER: builtins.int
    TRACES_FIELD_NUMBER: builtins.int
    DEBUGS_FIELD_NUMBER: builtins.int
    INFOS_FIELD_NUMBER: builtins.int
    WARNS_FIELD_NUMBER: builtins.int
    ERRORS_FIELD_NUMBER: builtins.int
    FATALS_FIELD_NUMBER: builtins.int
    logger_name: builtins.str
    traces: builtins.int
    debugs: builtins.int
    infos: builtins.int
    warns: builtins.int
    errors: builtins.int
    fatals: builtins.int
    def __init__(
        self,
        *,
        logger_name: builtins.str = ...,
        traces: builtins.int | None = ...,
        debugs: builtins.int | None = ...,
        infos: builtins.int | None = ...,
        warns: builtins.int | None = ...,
        errors: builtins.int | None = ...,
        fatals: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_debugs", b"_debugs", "_errors", b"_errors", "_fatals", b"_fatals", "_infos", b"_infos", "_traces", b"_traces", "_warns", b"_warns", "debugs", b"debugs", "errors", b"errors", "fatals", b"fatals", "infos", b"infos", "traces", b"traces", "warns", b"warns"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_debugs", b"_debugs", "_errors", b"_errors", "_fatals", b"_fatals", "_infos", b"_infos", "_traces", b"_traces", "_warns", b"_warns", "debugs", b"debugs", "errors", b"errors", "fatals", b"fatals", "infos", b"infos", "logger_name", b"logger_name", "traces", b"traces", "warns", b"warns"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_debugs", b"_debugs"]) -> typing_extensions.Literal["debugs"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_errors", b"_errors"]) -> typing_extensions.Literal["errors"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_fatals", b"_fatals"]) -> typing_extensions.Literal["fatals"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_infos", b"_infos"]) -> typing_extensions.Literal["infos"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_traces", b"_traces"]) -> typing_extensions.Literal["traces"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_warns", b"_warns"]) -> typing_extensions.Literal["warns"] | None: ...

global___Logger = Logger

@typing_extensions.final
class LoggerReportResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___LoggerReportResponse = LoggerReportResponse

@typing_extensions.final
class LimitResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _LimitPolicyNames:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _LimitPolicyNamesEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LimitResponse._LimitPolicyNames.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NOT_SET: LimitResponse._LimitPolicyNames.ValueType  # 0
        SECONDLY_ROLLING: LimitResponse._LimitPolicyNames.ValueType  # 1
        MINUTELY_ROLLING: LimitResponse._LimitPolicyNames.ValueType  # 3
        HOURLY_ROLLING: LimitResponse._LimitPolicyNames.ValueType  # 5
        DAILY_ROLLING: LimitResponse._LimitPolicyNames.ValueType  # 7
        MONTHLY_ROLLING: LimitResponse._LimitPolicyNames.ValueType  # 8
        INFINITE: LimitResponse._LimitPolicyNames.ValueType  # 9
        YEARLY_ROLLING: LimitResponse._LimitPolicyNames.ValueType  # 10

    class LimitPolicyNames(_LimitPolicyNames, metaclass=_LimitPolicyNamesEnumTypeWrapper): ...
    NOT_SET: LimitResponse.LimitPolicyNames.ValueType  # 0
    SECONDLY_ROLLING: LimitResponse.LimitPolicyNames.ValueType  # 1
    MINUTELY_ROLLING: LimitResponse.LimitPolicyNames.ValueType  # 3
    HOURLY_ROLLING: LimitResponse.LimitPolicyNames.ValueType  # 5
    DAILY_ROLLING: LimitResponse.LimitPolicyNames.ValueType  # 7
    MONTHLY_ROLLING: LimitResponse.LimitPolicyNames.ValueType  # 8
    INFINITE: LimitResponse.LimitPolicyNames.ValueType  # 9
    YEARLY_ROLLING: LimitResponse.LimitPolicyNames.ValueType  # 10

    PASSED_FIELD_NUMBER: builtins.int
    EXPIRES_AT_FIELD_NUMBER: builtins.int
    ENFORCED_GROUP_FIELD_NUMBER: builtins.int
    CURRENT_BUCKET_FIELD_NUMBER: builtins.int
    POLICY_GROUP_FIELD_NUMBER: builtins.int
    POLICY_NAME_FIELD_NUMBER: builtins.int
    POLICY_LIMIT_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    LIMIT_RESET_AT_FIELD_NUMBER: builtins.int
    SAFETY_LEVEL_FIELD_NUMBER: builtins.int
    passed: builtins.bool
    expires_at: builtins.int
    """for returnable: rtn this value"""
    enforced_group: builtins.str
    """events:pageview:homepage:123123"""
    current_bucket: builtins.int
    policy_group: builtins.str
    """events:pageview"""
    policy_name: global___LimitResponse.LimitPolicyNames.ValueType
    policy_limit: builtins.int
    amount: builtins.int
    limit_reset_at: builtins.int
    safety_level: global___LimitDefinition.SafetyLevel.ValueType
    def __init__(
        self,
        *,
        passed: builtins.bool = ...,
        expires_at: builtins.int = ...,
        enforced_group: builtins.str = ...,
        current_bucket: builtins.int = ...,
        policy_group: builtins.str = ...,
        policy_name: global___LimitResponse.LimitPolicyNames.ValueType = ...,
        policy_limit: builtins.int = ...,
        amount: builtins.int = ...,
        limit_reset_at: builtins.int = ...,
        safety_level: global___LimitDefinition.SafetyLevel.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["amount", b"amount", "current_bucket", b"current_bucket", "enforced_group", b"enforced_group", "expires_at", b"expires_at", "limit_reset_at", b"limit_reset_at", "passed", b"passed", "policy_group", b"policy_group", "policy_limit", b"policy_limit", "policy_name", b"policy_name", "safety_level", b"safety_level"]) -> None: ...

global___LimitResponse = LimitResponse

@typing_extensions.final
class LimitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _LimitCombiner:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _LimitCombinerEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LimitRequest._LimitCombiner.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NOT_SET: LimitRequest._LimitCombiner.ValueType  # 0
        MINIMUM: LimitRequest._LimitCombiner.ValueType  # 1
        MAXIMUM: LimitRequest._LimitCombiner.ValueType  # 2

    class LimitCombiner(_LimitCombiner, metaclass=_LimitCombinerEnumTypeWrapper): ...
    NOT_SET: LimitRequest.LimitCombiner.ValueType  # 0
    MINIMUM: LimitRequest.LimitCombiner.ValueType  # 1
    MAXIMUM: LimitRequest.LimitCombiner.ValueType  # 2

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    ACQUIRE_AMOUNT_FIELD_NUMBER: builtins.int
    GROUPS_FIELD_NUMBER: builtins.int
    LIMIT_COMBINER_FIELD_NUMBER: builtins.int
    ALLOW_PARTIAL_RESPONSE_FIELD_NUMBER: builtins.int
    SAFETY_LEVEL_FIELD_NUMBER: builtins.int
    account_id: builtins.int
    acquire_amount: builtins.int
    @property
    def groups(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    limit_combiner: global___LimitRequest.LimitCombiner.ValueType
    allow_partial_response: builtins.bool
    safety_level: global___LimitDefinition.SafetyLevel.ValueType
    """[default = L4_BEST_EFFORT];"""
    def __init__(
        self,
        *,
        account_id: builtins.int = ...,
        acquire_amount: builtins.int = ...,
        groups: collections.abc.Iterable[builtins.str] | None = ...,
        limit_combiner: global___LimitRequest.LimitCombiner.ValueType = ...,
        allow_partial_response: builtins.bool = ...,
        safety_level: global___LimitDefinition.SafetyLevel.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id", b"account_id", "acquire_amount", b"acquire_amount", "allow_partial_response", b"allow_partial_response", "groups", b"groups", "limit_combiner", b"limit_combiner", "safety_level", b"safety_level"]) -> None: ...

global___LimitRequest = LimitRequest

@typing_extensions.final
class ContextSet(google.protobuf.message.Message):
    """if the same Context type exists, last one wins"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXTS_FIELD_NUMBER: builtins.int
    @property
    def contexts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Context]: ...
    def __init__(
        self,
        *,
        contexts: collections.abc.Iterable[global___Context] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["contexts", b"contexts"]) -> None: ...

global___ContextSet = ContextSet

@typing_extensions.final
class Context(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class ValuesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___ConfigValue: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___ConfigValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    VALUES_FIELD_NUMBER: builtins.int
    type: builtins.str
    @property
    def values(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___ConfigValue]: ...
    def __init__(
        self,
        *,
        type: builtins.str | None = ...,
        values: collections.abc.Mapping[builtins.str, global___ConfigValue] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_type", b"_type", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_type", b"_type", "type", b"type", "values", b"values"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_type", b"_type"]) -> typing_extensions.Literal["type"] | None: ...

global___Context = Context

@typing_extensions.final
class Identity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class AttributesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    LOOKUP_FIELD_NUMBER: builtins.int
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    lookup: builtins.str
    @property
    def attributes(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        lookup: builtins.str | None = ...,
        attributes: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_lookup", b"_lookup", "lookup", b"lookup"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_lookup", b"_lookup", "attributes", b"attributes", "lookup", b"lookup"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_lookup", b"_lookup"]) -> typing_extensions.Literal["lookup"] | None: ...

global___Identity = Identity

@typing_extensions.final
class ConfigEvaluationMetaData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIG_ROW_INDEX_FIELD_NUMBER: builtins.int
    CONDITIONAL_VALUE_INDEX_FIELD_NUMBER: builtins.int
    WEIGHTED_VALUE_INDEX_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    VALUE_TYPE_FIELD_NUMBER: builtins.int
    config_row_index: builtins.int
    conditional_value_index: builtins.int
    weighted_value_index: builtins.int
    type: global___ConfigType.ValueType
    id: builtins.int
    value_type: global___Config.ValueType.ValueType
    def __init__(
        self,
        *,
        config_row_index: builtins.int | None = ...,
        conditional_value_index: builtins.int | None = ...,
        weighted_value_index: builtins.int | None = ...,
        type: global___ConfigType.ValueType | None = ...,
        id: builtins.int | None = ...,
        value_type: global___Config.ValueType.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_conditional_value_index", b"_conditional_value_index", "_config_row_index", b"_config_row_index", "_id", b"_id", "_type", b"_type", "_value_type", b"_value_type", "_weighted_value_index", b"_weighted_value_index", "conditional_value_index", b"conditional_value_index", "config_row_index", b"config_row_index", "id", b"id", "type", b"type", "value_type", b"value_type", "weighted_value_index", b"weighted_value_index"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_conditional_value_index", b"_conditional_value_index", "_config_row_index", b"_config_row_index", "_id", b"_id", "_type", b"_type", "_value_type", b"_value_type", "_weighted_value_index", b"_weighted_value_index", "conditional_value_index", b"conditional_value_index", "config_row_index", b"config_row_index", "id", b"id", "type", b"type", "value_type", b"value_type", "weighted_value_index", b"weighted_value_index"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_conditional_value_index", b"_conditional_value_index"]) -> typing_extensions.Literal["conditional_value_index"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_config_row_index", b"_config_row_index"]) -> typing_extensions.Literal["config_row_index"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_id", b"_id"]) -> typing_extensions.Literal["id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_type", b"_type"]) -> typing_extensions.Literal["type"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_value_type", b"_value_type"]) -> typing_extensions.Literal["value_type"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_weighted_value_index", b"_weighted_value_index"]) -> typing_extensions.Literal["weighted_value_index"] | None: ...

global___ConfigEvaluationMetaData = ConfigEvaluationMetaData

@typing_extensions.final
class ClientConfigValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INT_FIELD_NUMBER: builtins.int
    STRING_FIELD_NUMBER: builtins.int
    DOUBLE_FIELD_NUMBER: builtins.int
    BOOL_FIELD_NUMBER: builtins.int
    LOG_LEVEL_FIELD_NUMBER: builtins.int
    STRING_LIST_FIELD_NUMBER: builtins.int
    INT_RANGE_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    JSON_FIELD_NUMBER: builtins.int
    CONFIG_EVALUATION_METADATA_FIELD_NUMBER: builtins.int
    int: builtins.int
    string: builtins.str
    double: builtins.float
    bool: builtins.bool
    log_level: global___LogLevel.ValueType
    @property
    def string_list(self) -> global___StringList: ...
    @property
    def int_range(self) -> global___IntRange: ...
    @property
    def duration(self) -> global___ClientDuration: ...
    @property
    def json(self) -> global___Json: ...
    @property
    def config_evaluation_metadata(self) -> global___ConfigEvaluationMetaData: ...
    def __init__(
        self,
        *,
        int: builtins.int = ...,
        string: builtins.str = ...,
        double: builtins.float = ...,
        bool: builtins.bool = ...,
        log_level: global___LogLevel.ValueType = ...,
        string_list: global___StringList | None = ...,
        int_range: global___IntRange | None = ...,
        duration: global___ClientDuration | None = ...,
        json: global___Json | None = ...,
        config_evaluation_metadata: global___ConfigEvaluationMetaData | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_config_evaluation_metadata", b"_config_evaluation_metadata", "bool", b"bool", "config_evaluation_metadata", b"config_evaluation_metadata", "double", b"double", "duration", b"duration", "int", b"int", "int_range", b"int_range", "json", b"json", "log_level", b"log_level", "string", b"string", "string_list", b"string_list", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_config_evaluation_metadata", b"_config_evaluation_metadata", "bool", b"bool", "config_evaluation_metadata", b"config_evaluation_metadata", "double", b"double", "duration", b"duration", "int", b"int", "int_range", b"int_range", "json", b"json", "log_level", b"log_level", "string", b"string", "string_list", b"string_list", "type", b"type"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_config_evaluation_metadata", b"_config_evaluation_metadata"]) -> typing_extensions.Literal["config_evaluation_metadata"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["type", b"type"]) -> typing_extensions.Literal["int", "string", "double", "bool", "log_level", "string_list", "int_range", "duration", "json"] | None: ...

global___ClientConfigValue = ClientConfigValue

@typing_extensions.final
class ClientDuration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDS_FIELD_NUMBER: builtins.int
    NANOS_FIELD_NUMBER: builtins.int
    DEFINITION_FIELD_NUMBER: builtins.int
    seconds: builtins.int
    """the actual time is the sum of these, so 1.5 seconds would be seconds = 1, nanos = 500_000_000"""
    nanos: builtins.int
    definition: builtins.str
    def __init__(
        self,
        *,
        seconds: builtins.int = ...,
        nanos: builtins.int = ...,
        definition: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["definition", b"definition", "nanos", b"nanos", "seconds", b"seconds"]) -> None: ...

global___ClientDuration = ClientDuration

@typing_extensions.final
class ConfigEvaluations(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class ValuesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___ClientConfigValue: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___ClientConfigValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    VALUES_FIELD_NUMBER: builtins.int
    APIKEY_METADATA_FIELD_NUMBER: builtins.int
    DEFAULT_CONTEXT_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___ClientConfigValue]: ...
    @property
    def apikey_metadata(self) -> global___ApiKeyMetadata: ...
    @property
    def default_context(self) -> global___ContextSet: ...
    def __init__(
        self,
        *,
        values: collections.abc.Mapping[builtins.str, global___ClientConfigValue] | None = ...,
        apikey_metadata: global___ApiKeyMetadata | None = ...,
        default_context: global___ContextSet | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_apikey_metadata", b"_apikey_metadata", "_default_context", b"_default_context", "apikey_metadata", b"apikey_metadata", "default_context", b"default_context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_apikey_metadata", b"_apikey_metadata", "_default_context", b"_default_context", "apikey_metadata", b"apikey_metadata", "default_context", b"default_context", "values", b"values"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_apikey_metadata", b"_apikey_metadata"]) -> typing_extensions.Literal["apikey_metadata"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_default_context", b"_default_context"]) -> typing_extensions.Literal["default_context"] | None: ...

global___ConfigEvaluations = ConfigEvaluations

@typing_extensions.final
class LimitDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _SafetyLevel:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SafetyLevelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LimitDefinition._SafetyLevel.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NOT_SET: LimitDefinition._SafetyLevel.ValueType  # 0
        L4_BEST_EFFORT: LimitDefinition._SafetyLevel.ValueType  # 4
        L5_BOMBPROOF: LimitDefinition._SafetyLevel.ValueType  # 5

    class SafetyLevel(_SafetyLevel, metaclass=_SafetyLevelEnumTypeWrapper): ...
    NOT_SET: LimitDefinition.SafetyLevel.ValueType  # 0
    L4_BEST_EFFORT: LimitDefinition.SafetyLevel.ValueType  # 4
    L5_BOMBPROOF: LimitDefinition.SafetyLevel.ValueType  # 5

    POLICY_NAME_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    BURST_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    LAST_MODIFIED_FIELD_NUMBER: builtins.int
    RETURNABLE_FIELD_NUMBER: builtins.int
    SAFETY_LEVEL_FIELD_NUMBER: builtins.int
    policy_name: global___LimitResponse.LimitPolicyNames.ValueType
    limit: builtins.int
    burst: builtins.int
    account_id: builtins.int
    last_modified: builtins.int
    returnable: builtins.bool
    safety_level: global___LimitDefinition.SafetyLevel.ValueType
    """[default = L4_BEST_EFFORT]; // Overridable by request"""
    def __init__(
        self,
        *,
        policy_name: global___LimitResponse.LimitPolicyNames.ValueType = ...,
        limit: builtins.int = ...,
        burst: builtins.int = ...,
        account_id: builtins.int = ...,
        last_modified: builtins.int = ...,
        returnable: builtins.bool = ...,
        safety_level: global___LimitDefinition.SafetyLevel.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id", b"account_id", "burst", b"burst", "last_modified", b"last_modified", "limit", b"limit", "policy_name", b"policy_name", "returnable", b"returnable", "safety_level", b"safety_level"]) -> None: ...

global___LimitDefinition = LimitDefinition

@typing_extensions.final
class LimitDefinitions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEFINITIONS_FIELD_NUMBER: builtins.int
    @property
    def definitions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LimitDefinition]: ...
    def __init__(
        self,
        *,
        definitions: collections.abc.Iterable[global___LimitDefinition] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["definitions", b"definitions"]) -> None: ...

global___LimitDefinitions = LimitDefinitions

@typing_extensions.final
class BufferedRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    URI_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    LIMIT_GROUPS_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    FIFO_FIELD_NUMBER: builtins.int
    account_id: builtins.int
    method: builtins.str
    uri: builtins.str
    body: builtins.str
    @property
    def limit_groups(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    content_type: builtins.str
    fifo: builtins.bool
    def __init__(
        self,
        *,
        account_id: builtins.int = ...,
        method: builtins.str = ...,
        uri: builtins.str = ...,
        body: builtins.str = ...,
        limit_groups: collections.abc.Iterable[builtins.str] | None = ...,
        content_type: builtins.str = ...,
        fifo: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id", b"account_id", "body", b"body", "content_type", b"content_type", "fifo", b"fifo", "limit_groups", b"limit_groups", "method", b"method", "uri", b"uri"]) -> None: ...

global___BufferedRequest = BufferedRequest

@typing_extensions.final
class BatchRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    URI_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    LIMIT_GROUPS_FIELD_NUMBER: builtins.int
    BATCH_TEMPLATE_FIELD_NUMBER: builtins.int
    BATCH_SEPARATOR_FIELD_NUMBER: builtins.int
    account_id: builtins.int
    method: builtins.str
    uri: builtins.str
    body: builtins.str
    @property
    def limit_groups(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    batch_template: builtins.str
    batch_separator: builtins.str
    def __init__(
        self,
        *,
        account_id: builtins.int = ...,
        method: builtins.str = ...,
        uri: builtins.str = ...,
        body: builtins.str = ...,
        limit_groups: collections.abc.Iterable[builtins.str] | None = ...,
        batch_template: builtins.str = ...,
        batch_separator: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id", b"account_id", "batch_separator", b"batch_separator", "batch_template", b"batch_template", "body", b"body", "limit_groups", b"limit_groups", "method", b"method", "uri", b"uri"]) -> None: ...

global___BatchRequest = BatchRequest

@typing_extensions.final
class BasicResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message"]) -> None: ...

global___BasicResponse = BasicResponse

@typing_extensions.final
class CreationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    NEW_ID_FIELD_NUMBER: builtins.int
    message: builtins.str
    new_id: builtins.int
    def __init__(
        self,
        *,
        message: builtins.str = ...,
        new_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "new_id", b"new_id"]) -> None: ...

global___CreationResponse = CreationResponse

@typing_extensions.final
class IdBlock(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECT_ID_FIELD_NUMBER: builtins.int
    PROJECT_ENV_ID_FIELD_NUMBER: builtins.int
    SEQUENCE_NAME_FIELD_NUMBER: builtins.int
    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    project_id: builtins.int
    project_env_id: builtins.int
    sequence_name: builtins.str
    start: builtins.int
    end: builtins.int
    def __init__(
        self,
        *,
        project_id: builtins.int = ...,
        project_env_id: builtins.int = ...,
        sequence_name: builtins.str = ...,
        start: builtins.int = ...,
        end: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["end", b"end", "project_env_id", b"project_env_id", "project_id", b"project_id", "sequence_name", b"sequence_name", "start", b"start"]) -> None: ...

global___IdBlock = IdBlock

@typing_extensions.final
class IdBlockRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECT_ID_FIELD_NUMBER: builtins.int
    PROJECT_ENV_ID_FIELD_NUMBER: builtins.int
    SEQUENCE_NAME_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    project_id: builtins.int
    project_env_id: builtins.int
    sequence_name: builtins.str
    size: builtins.int
    def __init__(
        self,
        *,
        project_id: builtins.int = ...,
        project_env_id: builtins.int = ...,
        sequence_name: builtins.str = ...,
        size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["project_env_id", b"project_env_id", "project_id", b"project_id", "sequence_name", b"sequence_name", "size", b"size"]) -> None: ...

global___IdBlockRequest = IdBlockRequest

@typing_extensions.final
class ContextShape(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class FieldTypesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.int
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    FIELD_TYPES_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def field_types(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.int]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        field_types: collections.abc.Mapping[builtins.str, builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["field_types", b"field_types", "name", b"name"]) -> None: ...

global___ContextShape = ContextShape

@typing_extensions.final
class ContextShapes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHAPES_FIELD_NUMBER: builtins.int
    NAMESPACE_FIELD_NUMBER: builtins.int
    @property
    def shapes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ContextShape]: ...
    namespace: builtins.str
    def __init__(
        self,
        *,
        shapes: collections.abc.Iterable[global___ContextShape] | None = ...,
        namespace: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_namespace", b"_namespace", "namespace", b"namespace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_namespace", b"_namespace", "namespace", b"namespace", "shapes", b"shapes"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_namespace", b"_namespace"]) -> typing_extensions.Literal["namespace"] | None: ...

global___ContextShapes = ContextShapes

@typing_extensions.final
class EvaluatedKeys(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEYS_FIELD_NUMBER: builtins.int
    NAMESPACE_FIELD_NUMBER: builtins.int
    @property
    def keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    namespace: builtins.str
    def __init__(
        self,
        *,
        keys: collections.abc.Iterable[builtins.str] | None = ...,
        namespace: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_namespace", b"_namespace", "namespace", b"namespace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_namespace", b"_namespace", "keys", b"keys", "namespace", b"namespace"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_namespace", b"_namespace"]) -> typing_extensions.Literal["namespace"] | None: ...

global___EvaluatedKeys = EvaluatedKeys

@typing_extensions.final
class EvaluatedConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    CONFIG_VERSION_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    CONTEXT_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    key: builtins.str
    config_version: builtins.int
    @property
    def result(self) -> global___ConfigValue: ...
    @property
    def context(self) -> global___ContextSet: ...
    timestamp: builtins.int
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        config_version: builtins.int = ...,
        result: global___ConfigValue | None = ...,
        context: global___ContextSet | None = ...,
        timestamp: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["context", b"context", "result", b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["config_version", b"config_version", "context", b"context", "key", b"key", "result", b"result", "timestamp", b"timestamp"]) -> None: ...

global___EvaluatedConfig = EvaluatedConfig

@typing_extensions.final
class EvaluatedConfigs(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIGS_FIELD_NUMBER: builtins.int
    @property
    def configs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EvaluatedConfig]: ...
    def __init__(
        self,
        *,
        configs: collections.abc.Iterable[global___EvaluatedConfig] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["configs", b"configs"]) -> None: ...

global___EvaluatedConfigs = EvaluatedConfigs

@typing_extensions.final
class ConfigEvaluationCounter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Reason:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ConfigEvaluationCounter._Reason.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: ConfigEvaluationCounter._Reason.ValueType  # 0

    class Reason(_Reason, metaclass=_ReasonEnumTypeWrapper): ...
    UNKNOWN: ConfigEvaluationCounter.Reason.ValueType  # 0

    COUNT_FIELD_NUMBER: builtins.int
    CONFIG_ID_FIELD_NUMBER: builtins.int
    SELECTED_INDEX_FIELD_NUMBER: builtins.int
    SELECTED_VALUE_FIELD_NUMBER: builtins.int
    CONFIG_ROW_INDEX_FIELD_NUMBER: builtins.int
    CONDITIONAL_VALUE_INDEX_FIELD_NUMBER: builtins.int
    WEIGHTED_VALUE_INDEX_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    count: builtins.int
    config_id: builtins.int
    selected_index: builtins.int
    """index into the allowed-values list in the config"""
    @property
    def selected_value(self) -> global___ConfigValue: ...
    config_row_index: builtins.int
    """which row matched"""
    conditional_value_index: builtins.int
    """which ConditionalValue in the row matched?"""
    weighted_value_index: builtins.int
    """index into the weighted value array"""
    reason: global___ConfigEvaluationCounter.Reason.ValueType
    def __init__(
        self,
        *,
        count: builtins.int = ...,
        config_id: builtins.int | None = ...,
        selected_index: builtins.int | None = ...,
        selected_value: global___ConfigValue | None = ...,
        config_row_index: builtins.int | None = ...,
        conditional_value_index: builtins.int | None = ...,
        weighted_value_index: builtins.int | None = ...,
        reason: global___ConfigEvaluationCounter.Reason.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_conditional_value_index", b"_conditional_value_index", "_config_id", b"_config_id", "_config_row_index", b"_config_row_index", "_selected_index", b"_selected_index", "_selected_value", b"_selected_value", "_weighted_value_index", b"_weighted_value_index", "conditional_value_index", b"conditional_value_index", "config_id", b"config_id", "config_row_index", b"config_row_index", "selected_index", b"selected_index", "selected_value", b"selected_value", "weighted_value_index", b"weighted_value_index"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_conditional_value_index", b"_conditional_value_index", "_config_id", b"_config_id", "_config_row_index", b"_config_row_index", "_selected_index", b"_selected_index", "_selected_value", b"_selected_value", "_weighted_value_index", b"_weighted_value_index", "conditional_value_index", b"conditional_value_index", "config_id", b"config_id", "config_row_index", b"config_row_index", "count", b"count", "reason", b"reason", "selected_index", b"selected_index", "selected_value", b"selected_value", "weighted_value_index", b"weighted_value_index"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_conditional_value_index", b"_conditional_value_index"]) -> typing_extensions.Literal["conditional_value_index"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_config_id", b"_config_id"]) -> typing_extensions.Literal["config_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_config_row_index", b"_config_row_index"]) -> typing_extensions.Literal["config_row_index"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_selected_index", b"_selected_index"]) -> typing_extensions.Literal["selected_index"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_selected_value", b"_selected_value"]) -> typing_extensions.Literal["selected_value"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_weighted_value_index", b"_weighted_value_index"]) -> typing_extensions.Literal["weighted_value_index"] | None: ...

global___ConfigEvaluationCounter = ConfigEvaluationCounter

@typing_extensions.final
class ConfigEvaluationSummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    COUNTERS_FIELD_NUMBER: builtins.int
    key: builtins.str
    type: global___ConfigType.ValueType
    """type of config eval"""
    @property
    def counters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ConfigEvaluationCounter]: ...
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        type: global___ConfigType.ValueType = ...,
        counters: collections.abc.Iterable[global___ConfigEvaluationCounter] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["counters", b"counters", "key", b"key", "type", b"type"]) -> None: ...

global___ConfigEvaluationSummary = ConfigEvaluationSummary

@typing_extensions.final
class ConfigEvaluationSummaries(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    SUMMARIES_FIELD_NUMBER: builtins.int
    start: builtins.int
    end: builtins.int
    @property
    def summaries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ConfigEvaluationSummary]: ...
    def __init__(
        self,
        *,
        start: builtins.int = ...,
        end: builtins.int = ...,
        summaries: collections.abc.Iterable[global___ConfigEvaluationSummary] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["end", b"end", "start", b"start", "summaries", b"summaries"]) -> None: ...

global___ConfigEvaluationSummaries = ConfigEvaluationSummaries

@typing_extensions.final
class LoggersTelemetryEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOGGERS_FIELD_NUMBER: builtins.int
    START_AT_FIELD_NUMBER: builtins.int
    END_AT_FIELD_NUMBER: builtins.int
    @property
    def loggers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Logger]: ...
    start_at: builtins.int
    end_at: builtins.int
    def __init__(
        self,
        *,
        loggers: collections.abc.Iterable[global___Logger] | None = ...,
        start_at: builtins.int = ...,
        end_at: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["end_at", b"end_at", "loggers", b"loggers", "start_at", b"start_at"]) -> None: ...

global___LoggersTelemetryEvent = LoggersTelemetryEvent

@typing_extensions.final
class TelemetryEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUMMARIES_FIELD_NUMBER: builtins.int
    EXAMPLE_CONTEXTS_FIELD_NUMBER: builtins.int
    CLIENT_STATS_FIELD_NUMBER: builtins.int
    LOGGERS_FIELD_NUMBER: builtins.int
    CONTEXT_SHAPES_FIELD_NUMBER: builtins.int
    @property
    def summaries(self) -> global___ConfigEvaluationSummaries: ...
    @property
    def example_contexts(self) -> global___ExampleContexts: ...
    @property
    def client_stats(self) -> global___ClientStats: ...
    @property
    def loggers(self) -> global___LoggersTelemetryEvent: ...
    @property
    def context_shapes(self) -> global___ContextShapes: ...
    def __init__(
        self,
        *,
        summaries: global___ConfigEvaluationSummaries | None = ...,
        example_contexts: global___ExampleContexts | None = ...,
        client_stats: global___ClientStats | None = ...,
        loggers: global___LoggersTelemetryEvent | None = ...,
        context_shapes: global___ContextShapes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["client_stats", b"client_stats", "context_shapes", b"context_shapes", "example_contexts", b"example_contexts", "loggers", b"loggers", "payload", b"payload", "summaries", b"summaries"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["client_stats", b"client_stats", "context_shapes", b"context_shapes", "example_contexts", b"example_contexts", "loggers", b"loggers", "payload", b"payload", "summaries", b"summaries"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["payload", b"payload"]) -> typing_extensions.Literal["summaries", "example_contexts", "client_stats", "loggers", "context_shapes"] | None: ...

global___TelemetryEvent = TelemetryEvent

@typing_extensions.final
class TelemetryEvents(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSTANCE_HASH_FIELD_NUMBER: builtins.int
    EVENTS_FIELD_NUMBER: builtins.int
    instance_hash: builtins.str
    """random UUID generated on startup - represents the server so we can aggregate"""
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TelemetryEvent]: ...
    def __init__(
        self,
        *,
        instance_hash: builtins.str = ...,
        events: collections.abc.Iterable[global___TelemetryEvent] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["events", b"events", "instance_hash", b"instance_hash"]) -> None: ...

global___TelemetryEvents = TelemetryEvents

@typing_extensions.final
class TelemetryEventsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["success", b"success"]) -> None: ...

global___TelemetryEventsResponse = TelemetryEventsResponse

@typing_extensions.final
class ExampleContexts(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXAMPLES_FIELD_NUMBER: builtins.int
    @property
    def examples(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ExampleContext]: ...
    def __init__(
        self,
        *,
        examples: collections.abc.Iterable[global___ExampleContext] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["examples", b"examples"]) -> None: ...

global___ExampleContexts = ExampleContexts

@typing_extensions.final
class ExampleContext(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    CONTEXTSET_FIELD_NUMBER: builtins.int
    timestamp: builtins.int
    @property
    def contextSet(self) -> global___ContextSet: ...
    def __init__(
        self,
        *,
        timestamp: builtins.int = ...,
        contextSet: global___ContextSet | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["contextSet", b"contextSet"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["contextSet", b"contextSet", "timestamp", b"timestamp"]) -> None: ...

global___ExampleContext = ExampleContext

@typing_extensions.final
class ClientStats(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    DROPPED_EVENT_COUNT_FIELD_NUMBER: builtins.int
    start: builtins.int
    end: builtins.int
    dropped_event_count: builtins.int
    def __init__(
        self,
        *,
        start: builtins.int = ...,
        end: builtins.int = ...,
        dropped_event_count: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["dropped_event_count", b"dropped_event_count", "end", b"end", "start", b"start"]) -> None: ...

global___ClientStats = ClientStats
