name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - context
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: "[${{matrix.python}}] CI"
    strategy:
      matrix:
        python: ["3.10.10", "3.11.2"]
    steps:
      - name: Checkout repo + submodules
        uses: actions/checkout@v2.4.0
        with:
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run tests
        run: python -m pytest -k 'not integration'
        env:
          PREFAB_INTEGRATION_TEST_API_KEY: ${{ secrets.PREFAB_INTEGRATION_TEST_API_KEY }}
