name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - context
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: "[${{matrix.python}}] CI"
    strategy:
      matrix:
        python: ["3.9.15", "3.10.10", "3.11.2"]
        mmh3-version: [">=3.0.0,<4.0.0", ">=4.0.0,<5.0.0"]
    steps:
      - name: Checkout repo + submodules
        uses: actions/checkout@v2.4.0
        with:
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true

      - name: Install dependencies
        run: |
          poetry add mmh3${{ matrix.mmh3-version }}
          poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest -k 'not integration'
        env:
          PREFAB_INTEGRATION_TEST_API_KEY: ${{ secrets.PREFAB_INTEGRATION_TEST_API_KEY }}
